# 2025-2026 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)

from odoo import api, fields, models
from odoo.exceptions import UserError


class AccountMove(models.Model):
    _inherit = "account.move"

    invoiceset_id = fields.Many2one(
        comodel_name="account.invoiceset",
        string="Invoice Set",
        index=True,
        ondelete="restrict",
        copy=False,
        readonly=True,
        check_company=False,
    )

    @api.ondelete(at_uninstall=False)
    def _unlink_except_linked_to_invoiceset(self):
        """Block deleting an invoice that belongs to an invoice set.

        Invoices generated by an invoice set must only be removed through the
        set's own cancellation flow (which passes ``cancelling_invoiceset`` in
        the context). Any other attempt to delete them is rejected so the link
        between the set and its invoices stays consistent.
        """
        if self.env.context.get("cancelling_invoiceset"):
            return
        linked = self.filtered("invoiceset_id")
        if linked:
            raise UserError(
                self.env._(
                    "It is not possible to delete an invoice that belongs to "
                    "an invoice set. Cancel the invoice set instead.\n\n"
                    "Invoices: %(invoices)s\nInvoice sets: %(sets)s",
                    invoices=", ".join(
                        linked.mapped(lambda m: m.name or self.env._("Draft"))
                    ),
                    sets=", ".join(linked.mapped("invoiceset_id.alphanum_code")),
                )
            )
